### ISSUE TITLE
node执行scan+fix报错`no such file or directory, open`

### ISSUE THREAD

**Issue by xmsz-stu** [alibaba/f2e-spec#112]
背景
目录结构
- src
  - services
- script
  - a.js 

- 有个./script/a.js里运行 f2elint.scan
```
 await f2elint.scan({
    cwd: '/src/services',
    include: '.',
    fix: true,
    quiet: false,
    outputReport: true,
  });
```

如果fix为false, 则正常
但是如果fix为true, 则报错`Error: ENOENT: no such file or directory, open 'h5.ts'`
```
Error: ENOENT: no such file or directory, open 'h5.ts'
    at Object.openSync (node:fs:595:3)
    at Object.readFileSync (node:fs:463:35)
    at /home/xmsz/code/card/node_modules/f2elint/lib/actions/scan.js:128:43
    at step (/home/xmsz/code/card/node_modules/f2elint/lib/actions/scan.js:63:23)
    at Object.next (/home/xmsz/code/card/node_modules/f2elint/lib/actions/scan.js:44:53)
    at /home/xmsz/code/card/node_modules/f2elint/lib/actions/scan.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (/home/xmsz/code/card/node_modules/f2elint/lib/actions/scan.js:34:12)
    at /home/xmsz/code/card/node_modules/f2elint/lib/actions/scan.js:91:48
    at /home/xmsz/code/card/node_modules/f2elint/lib/index.js:75:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'h5.ts'
}
```
然后我看源码里的
```
if (!!files_1_1.done) return [3, 5];
                filepath = files_1_1.value;
                text = fs_extra_1.default.readFileSync(filepath, 'utf8');
                return [4, prettier_1.default.resolveConfig(filepath)];
```
这里的filepath确实只有`h5.ts` 没有拼上cwd

**Comment by guoyunhe** [comment]
请更新到最新版本：

```
tnpx f2elint@latest
```
